[Interface]
PrivateKey = MNTCro7zPys2IZyxqprpGeVMYLDXDPF6xv6XMEZsA1Q=
Address = 172.16.250.2/24

[Peer]
PublicKey = D2xtJpoZVuM8unhjrgFXu5NBh1eNtfpgiCvuX0CIYwo=
Endpoint = 10.21.21.131:51820
AllowedIPs = 172.16.250.0/24
PersistentKeepalive = 25